get:
  tags:
  - User
  operationId: getSettings
  summary: The user's app settings
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            $ref: ../../../components/schemas/UserSettings.yaml
