get:
  tags:
  - Recipes
  operationId: listFavoriteRecipes
  summary: Recipes the user favourited
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            type: array
            items: {}
